name: mail_check
description: A Flutter package for both android, iOS and web. which provides email validate and make email suggestion.
version: 2.0.0
homepage: https://github.com/iOSHiepLe/mail_check

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/mail_check/assets/all_email_provider_domains.txt